feat(protection): Separate interactions from ACE_MainActions and put them on corresponding members
team-gsri/GSRI-VIP pull request #8
Opened 2022-09-18 16:19 UTC by PhileasLX

#7

2022-09-19 08:53 UTC, ArwynFr reviewed
/delegate @ImplicitDeny 😄

2022-09-22 15:30 UTC, ImplicitDeny requested changes
A few formatting mistakes to fix

2022-09-22 15:30 UTC, ImplicitDeny commented on addons/gsri_vip/functions/protection/fn_vipCheckForGear.sqf
> +			}
Missing ;

2022-09-22 15:30 UTC, ImplicitDeny commented on addons/gsri_vip/functions/protection/fn_vipCheckForGear.sqf
>  		};
Bad indent on case closing brackets

2022-10-19 19:47 UTC, PhileasLX commented on addons/gsri_vip/functions/protection/fn_vipCheckForGear.sqf
> +			}
It has been fixed.

2022-10-22 14:45 UTC, ImplicitDeny requested changes
A few fixes

2022-10-22 14:45 UTC, ImplicitDeny commented on addons/gsri_vip/functions/core/fn_initVip.sqf
>  };
missing LF

2022-10-22 14:45 UTC, ImplicitDeny commented on addons/gsri_vip/functions/protection/fn_vipCheckForGear.sqf
>  _actions;
Missing LF

2022-10-22 14:45 UTC, ImplicitDeny commented on addons/gsri_vip/functions/protection/fn_vipEquipGear.sqf
> +if (_gearToEquip isEqualTo "") exitWith { diag_log ["GSRI VIP: vipEquipGear: no _gearToEquip."] };
unnecessary [ ]

2022-10-22 14:45 UTC, ImplicitDeny commented on addons/gsri_vip/functions/protection/fn_vipEquipGearFailure.sqf
> +["vipChangeSpeedCoeff", [_player, 1]] call CBA_fnc_globalEvent;
Missing LF

2022-10-22 14:45 UTC, ImplicitDeny commented on addons/gsri_vip/functions/protection/fn_vipEquipGearSuccess.sqf
> +["vipChangeSpeedCoeff", [_player, 1]] call CBA_fnc_globalEvent;
Missing LF

2022-10-22 14:45 UTC, ImplicitDeny commented on addons/gsri_vip/functions/protection/fn_vipTryEquipGear.sqf
> +[_duration, [_target, _player, _gear, _currentAnimName] , GSRI_fnc_vipEquipGearSuccess, GSRI_fnc_vipEquipGearFailure, localize "STR_VIP_settingUpProtection"] call ace_common_fnc_progressBar;
Missing LF

2022-10-23 16:14 UTC, ImplicitDeny approved these changes

2022-10-23 16:18 UTC, merged